# version: 2

# updates:
#   - package-ecosystem: "pip"
#     directory: "/"
#     schedule:
#       interval: "monthly"
#     open-pull-requests-limit: 1
#     groups:
#       all-dependencies:
#         patterns:
#           - "*"
#     commit-message:
#       prefix: "chore"
#       include: "scope"

#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "monthly"
#     open-pull-requests-limit: 1
#     groups:
#       all-actions:
#         patterns:
#           - "*"
#     commit-message:
#       prefix: "chore"
#       include: "scope"
