global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "payzee"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: "/metrics"

#   - job_name: "redis"
#     static_configs:
#       - targets: ["redis:6379"]

#   - job_name: "prometheus"
#     static_configs:
#       - targets: ["prometheus:9090"]

#   - job_name: "grafana"
#     static_configs:
#       - targets: ["grafana:3000"]
