[project]
name = "payzee"
version = "1.0.0"
description = "Pay Easy, Payzee"
authors = [
    {name = "Areeb Ahmed", email = "hi@areeb.dev"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn (>=0.34.2,<0.35.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
