name: Deploy to DigitalOcean

on:
  push:
    branches:
      - develop
    paths:
      - 'docker/**'
      - 'middleware/**'
      - 'db/**'
      - 'models/**'
      - 'routes/**'
      # - 'utils/**'
      # - 'tests/**'
      - 'app.py'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'docker-compose.yaml'
      - '.github/workflows/deploy.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tests-passed: ${{ steps.check-tests.outputs.passed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        id: tests
        run: poetry run pytest tests/
        continue-on-error: true
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Check if tests passed
        id: check-tests
        run: echo "passed=${{ steps.tests.outcome == 'success' }}" >> $GITHUB_OUTPUT

  docker:
    runs-on: ubuntu-latest
    needs: setup
    if: needs.setup.outputs.tests-passed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: areebahmeddd/payzee-api
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Trigger DigitalOcean Deployment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DO_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_ID }}/deployments"
