name: Deploy to DigitalOcean

on:
  push:
    branches:
      - develop
    paths:
      - 'docker/**'
      - 'middleware/**'
      - 'db/**'
      - 'models/**'
      - 'routes/**'
    #   - 'utils/**'
    #   - 'tests/**'
      - 'app.py'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'docker-compose.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.repository == '1MindLabs/payzee-api'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        id: tests
        run: poetry run pytest tests/
        continue-on-error: true

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        if: steps.tests.outcome == 'success'
        with:
          image: areebahmeddd/payzee-api
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Trigger DigitalOcean Deployment
        if: steps.tests.outcome == 'success'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DO_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_ID }}/deployments"
