name: Skip Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Dockerfile'
      - '.github/workflows/deploy.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Skip deployment
      run: echo "Deployment skipped."
